### ISSUE TITLE
Search terms not respecting word boundaries

### ISSUE THREAD

**Issue by melange396** [cmu-delphi/signal_documentation#35]
Its not clear to me which behavior would be best here, but as an example: Someone might search for "age" because they might be looking for senior citizen or juvenile demographic information.  That search returns many non-age related results, because they match on the substring "age" found within "percentage", which is a very common term in our signal set.

We might want to only do substring matches when a wildcard token is provided (like "`age`" does not match "percentage" but "`*age`" or "`*age*`" does.

I'm not familiar with how this is being done behind the scenes, but maybe there is some tokenization that needs to happen on the search corpus, or perhaps the inclusion of the regex word boundary marker "`\b`" into search conditions, or a number of other possibilities.

[edited to clarify asterisks in the sample search strings, which were previously interpreted as "emboldening" and removed by markdown]

**Comment by BrainIsDead** [comment]
Did not get what should be done, could you pls formulate the requirements

**Comment by melange396** [comment]
maybe changing the search to something like this?  https://stackoverflow.com/questions/2958214/django-filter-icontains-match-whole-words-only/4024355#4024355

**Comment by rlunde** [comment]
Some additional context - the most likely thing that users want to do is to search for whole words rather than substrings - many UIs provide a mechanism for the user to specify their intent, where they say whether they are looking for words or substrings. (e.g. the [ ] match whole words only" option you sometimes see in a UI). It could be very frustrating to look for a small word that is often a substring if we don't have a way to do that.

In Django, when we do this type of filter:

        queries: list[Q] = [Q((f'{field}__icontains', value)) for field in ['name', 'description', 'short_description']]

The "__icontains" is a case insensitive substring match for value (as far as I can tell). So if the user specified "a" as the search value, it would find any string containing any word that contained an "a". It passes it to MySQL like:

SELECT *
FROM table 
WHERE field LIKE '%a%'

In MySQL, if you wanted to filter strings just containing the word "a" (so it would match "a cat" but not "cat"), you would use '\\ba\\b'. (It's my understanding that django passes regex values straight through to the underlying DB, so the form would be different if we used Postgres.) You would also need to use REGEX rather than LIKE:

SELECT *
FROM table 
WHERE keywords REGEXP '\\ba\\b'

It appears django has a way to do that like this, using __iregex rather than __icontains, so we might do something like:

queries: list[Q] = [Q((f'{field}__iregex', f'\b{value}\b')) for field in ['name', 'description', 'short_description']]

That leaves us with a UI/UX question to answer, which is whether to provide a way for people to search for substrings if they want to. If we do, we'd probably do something like a form field "[x] find whole words" that defaults to checked?
